const key=
"BQCZvBbz1iGtG1rHWznkEUSv3FFbMYGARXnkayIXgTtQ7As3KrtALLty7haRLqVcMeWbn1LnbUFmRA2m-IMdg__NGeRnOu7p-vhrGZfb5_C-BD3PyduzRprJ9wWs74BfU9SmX6gF_Yo0smVCrbknhHDuhv_hy9uU1KUqVZauNTgRDIRGnbjUzzFVlMU0yK67nB4lKSc5kB_FLsWuUabxBo3xpnd_";

export default key